"""add title to deal_activities

Revision ID: 466aea3dc2c0
Revises: 401bc3e9ddc3
Create Date: 2026-07-24 16:14:41.062337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466aea3dc2c0'
down_revision: Union[str, Sequence[str], None] = '401bc3e9ddc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_activities', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_activities', 'title')
    # ### end Alembic commands ###
