"""is_active/is_delete on base, soft-delete users

Revision ID: 6853f7269cee
Revises: a4f7c1e9b2d6
Create Date: 2026-07-20 19:35:46.789055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6853f7269cee'
down_revision: Union[str, Sequence[str], None] = 'a4f7c1e9b2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('accounts', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contacts', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('contacts', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('deal_stage_history', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('deal_stage_history', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('deals', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('deals', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lead_activities', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('lead_activities', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lead_contacts', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('lead_contacts', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leads', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('leads', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_delete')
    op.drop_column('refresh_tokens', 'is_delete')
    op.drop_column('refresh_tokens', 'is_active')
    op.drop_column('leads', 'is_delete')
    op.drop_column('leads', 'is_active')
    op.drop_column('lead_contacts', 'is_delete')
    op.drop_column('lead_contacts', 'is_active')
    op.drop_column('lead_activities', 'is_delete')
    op.drop_column('lead_activities', 'is_active')
    op.drop_column('deals', 'is_delete')
    op.drop_column('deals', 'is_active')
    op.drop_column('deal_stage_history', 'is_delete')
    op.drop_column('deal_stage_history', 'is_active')
    op.drop_column('contacts', 'is_delete')
    op.drop_column('contacts', 'is_active')
    op.drop_column('accounts', 'is_delete')
    op.drop_column('accounts', 'is_active')
    # ### end Alembic commands ###
