"""unique email on contacts and lead_contacts

Revision ID: 84bf9037d7d8
Revises: bebc0b4f9733
Create Date: 2026-07-24 15:07:04.669333

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '84bf9037d7d8'
down_revision: Union[str, Sequence[str], None] = 'bebc0b4f9733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Pre-existing duplicate emails would block the new unique indexes below.
    # For each duplicate, keep the newest row's email and clear it (NULL) on
    # the older row(s) rather than deleting any data.
    op.execute("""
        UPDATE contacts SET email = NULL WHERE id IN (
            SELECT id FROM (
                SELECT id, row_number() OVER (PARTITION BY email ORDER BY created_at DESC, id DESC) AS rn
                FROM contacts WHERE email IS NOT NULL
            ) ranked WHERE rn > 1
        )
    """)
    op.execute("""
        UPDATE lead_contacts SET email = NULL WHERE id IN (
            SELECT id FROM (
                SELECT id, row_number() OVER (PARTITION BY email ORDER BY created_at DESC, id DESC) AS rn
                FROM lead_contacts WHERE email IS NOT NULL
            ) ranked WHERE rn > 1
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_lead_contacts_email'), 'lead_contacts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_contacts_email'), table_name='lead_contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    # ### end Alembic commands ###
