"""create deals and deal_stage_history tables

Revision ID: 9fe2cb108395
Revises: 41527295d3be
Create Date: 2026-07-15 18:13:58.796868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9fe2cb108395'
down_revision: Union[str, Sequence[str], None] = '41527295d3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('stage', sa.Enum('received_requirements', 'qualified_to_buy', 'evaluation', 'proposals', 'contracts', 'closed_won', 'closed_lost', 'cold_deals', name='deal_stage'), server_default='received_requirements', nullable=False),
    sa.Column('cold_reason', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_account_id'), 'deals', ['account_id'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_table('deal_stage_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column(
        'from_stage',
        postgresql.ENUM(
            'received_requirements', 'qualified_to_buy', 'evaluation', 'proposals', 'contracts',
            'closed_won', 'closed_lost', 'cold_deals', name='deal_stage', create_type=False,
        ),
        nullable=True,
    ),
    sa.Column(
        'to_stage',
        postgresql.ENUM(
            'received_requirements', 'qualified_to_buy', 'evaluation', 'proposals', 'contracts',
            'closed_won', 'closed_lost', 'cold_deals', name='deal_stage', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_stage_history_deal_id'), 'deal_stage_history', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_stage_history_deal_id'), table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_account_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
