"""create accounts table and lead is_converted

Revision ID: d8d44e545baa
Revises: c7c9f495d5f7
Create Date: 2026-07-15 15:19:38.881208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd8d44e545baa'
down_revision: Union[str, Sequence[str], None] = 'c7c9f495d5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column(
        'tier',
        postgresql.ENUM('diamond', 'gold', 'silver', 'bronze', name='lead_tier', create_type=False),
        nullable=False,
    ),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.add_column('leads', sa.Column('is_converted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'is_converted')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
